services:
  - type: web
    name: mugshot-matcher
    env: node
    plan: starter
    buildCommand: |
      # Pre-build directory verification
      echo "Verifying directories..."
      if [ ! -d "/data" ]; then
        echo "Error: /data directory not found or not mounted"
        exit 1
      fi
      if [ ! -w "/data" ]; then
        echo "Error: /data directory is not writable"
        exit 1
      fi
      if [ ! -d "$SOURCE_DATA_DIR" ]; then
        echo "Error: Source data directory not found: $SOURCE_DATA_DIR"
        exit 1
      fi
      
      # Note: sorted_mugshots.csv is now transferred manually using the wormhole CLI tool
      # after deployment, not during the build process
      
      # Install dependencies
      echo "Installing dependencies..."
      npm install
      
      # Run data copy script
      echo "Running copy-data script..."
      node scripts/copy-data.js
      if [ $? -ne 0 ]; then
        echo "Error: Failed to copy data files"
        exit 1
      fi
      
      # Note: sorted_mugshots.csv will be transferred manually after deployment
      # using the wormhole CLI tool, so we don't check for it during build
      
      # Validate CSV content
      echo "Validating CSV files..."
      node scripts/validate-data.js
      if [ $? -ne 0 ]; then
        echo "Error: CSV validation failed"
        exit 1
      fi
      
      # Note: File permission checks for sorted_mugshots.csv are not needed during build
      # as the file will be transferred manually after deployment
      
      # Build application
      echo "Building application..."
      npm run build
    startCommand: npm start
    healthCheckPath: /api/inmates
    healthCheckTimeout: 60
    healthCheck:
      - path: /api/inmates
        interval: 30s
        timeout: 10s
        grace_period: 60s
      # Health check for the CSV file after manual transfer via wormhole
      - path: /data/sorted_mugshots.csv
        type: file_check
        interval: 60s
      - path: /data
        type: disk_check
        threshold_percent: 90
    envVars:
      # Path to the CSV file after manual transfer via wormhole
      - key: MUGSHOTS_CSV_PATH
        value: /data/sorted_mugshots.csv
        sync: false
      - key: NODE_ENV
        value: production
      - key: SOURCE_DATA_DIR
        value: /opt/render/project/src/mugshotscripts
      - key: DATA_DIR
        value: /data
      - key: ENABLE_VERBOSE_LOGGING
        value: "true"
      - key: RENDER_ENVIRONMENT
        value: "true"
    
    # Static file handling for Next.js
    staticPublishPath: .next/static
    routes:
      - type: rewrite
        source: /_next/static/*
        destination: /static/*
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html

    # Disk configuration for storing CSV and DB files
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
      permissions: "0755"
      backup:
        enabled: true
        schedule: "0 0 * * *"
        retention: 7d

    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
        compress: "true"
      destination:
        type: papertrail
        retention: 7d
        verbosity: info