services:
  - type: web
    name: mugshot-matcher
    env: node
    plan: starter
    buildCommand: npm install; npm run build
    startCommand: npm start
    healthCheckPath: /api/inmates
    envVars:
      - key: MUGSHOTS_CSV_PATH
        value: /data/sorted_mugshots.csv
        sync: false
      - key: MUGSHOTS_DB_PATH
        value: /data/mugshots.db
        sync: false
      - key: NODE_ENV
        value: production
      - key: SOURCE_DATA_DIR
        value: /opt/render/project/src/mugshotscripts
      - key: RENDER_ENVIRONMENT
        value: "true"
    
    # Static file handling for Next.js
    staticPublishPath: .next/static
    routes:
      - type: rewrite
        source: /_next/static/*
        destination: /static/*
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html

    # Disk configuration for storing CSV and DB files
    disk:
      name: data
      mountPath: /data
      sizeGB: 1